### ISSUE TITLE
custom keyboard shortcuts don't work

### ISSUE THREAD

**Issue by cristianmtr** [klaussinani/tusk#258]
**Describe the bug**

Trying to change keyboard shortcuts to use something other than Ctrl+Alt for global commands.

Tried Ctrl+Win, Ctrl+Super, Shift+Alt. None work.

Tried restarting Tusk too.

**Expected behavior**

They should be updated.

**Technical Info (please complete the following information)**
 - OS: 
```
cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

`Linux cristian-work 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

 - Tusk Version: 0.23.0

**Comment by ei8fdb** [comment]
I've got the same issue. 

## Tusk version
Version: 0.23.0
Electron: 4.2.2
Chrome: 69.0.3497.128
Node: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.3.0-7625-generic

## OS details
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Comment by ei8fdb** [comment]
The (current) answer to the "shortcut keys not working" issue is to use the original Evernote interface. This is because according to @klaussinani the new interface (Beta editor included) is still under development. The new interface will be supported when it replaces the original interface. 

To get shortcuts working change back to the original interface like this

<img alt="" width="50%" src="https://user-images.githubusercontent.com/12670537/41428142-e0588738-7011-11e8-8f92-a8e796fc179e.png">

I've done this and confirmed I can now use shortcuts (ctrl+shirt+l = add link)
